site_name: KIT Lernfeld 2 (technisch)

theme:
  name: material
  language: de
  font: false
  favicon: bilder/favicon.png
  logo: bilder/logo.png

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences

plugins:
  - include-markdown

extra_css:
    - 'extra.css'

use_directory_urls: false

repo_url: https://github.com/herr-nm/MMBbS_KIT_LF02

site_url: https://herr-nm.github.io/MMBbS_KIT_LF02/

nav:
    - Einleitung zum LF2: 'index.md'
    - Kapitel 00 - Organisatorisches: 'kapitel_00.md'
    - Kapitel 01 - Propädeutikum: 'kapitel_01.md'
    - Kapitel 02 - IT-Systeme auswählen: 'kapitel_02.md'
    - Kapitel 03 - Netzwerkspeicher dimensionieren: 'kapitel_03.md'
    - Kapitel 04 - IT-Systeme in Betrieb nehmen: 'kapitel_04.md'
    - Kapitel 05 - Sensoren auslesen: 'kapitel_05.md'
    - Kapitel 06 - Aktoren ansteuern: 'kapitel_06.md'